Blog post for beginning bioinformaticians
2020F-usfca-btec-640/2020F-usfca-btec-640.github.io pull request #1
Opened 2020-11-03 20:26 UTC by FNTrejo8

Please take a look, I'd welcome any suggestions. Thanks! @naupaka @melt6457 @mhaliz

2020-11-03 20:32 UTC, naupaka commented
We'll get a formal review going in a bit, but a few quick fixes:
* Please remove the DS_Store file from the PR
* Add your name somewhere in the post
* The alt-text for the images should say what the images are of (e.g. [see here](https://en.wikipedia.org/wiki/Alt_attribute))

2020-11-05 18:07 UTC, FNTrejo8 commented
Remove DS_Store file: Fixed by b0a4dcb2e98c9c6073d3005a40cf8c957f84440e
Add name and alt-text: Fixed by 852d040bb356ba70ac25976c2301337961f55cd5

2020-11-15 07:10 UTC, emhumphrey approved these changes
Hey Naailah,
This looks great! I found it to be very thorough, concise, and informative! I read through this a couple of times seeing if there was anything I could think of that you could add to improve it and I really think you covered it all. I also really liked that you had so many visual images as examples to represent what you were talking about as well.

2020-11-20 01:56 UTC, naupaka requested changes
The post looks great! Please remove the .DS_Store file in the assets directory so that we avoid any merge conflicts. Then this should be ready to merge!

2020-11-21 02:54 UTC, FNTrejo8 commented
Removed .DS_Store from assets directory, fixed by a1222a8cdb939c368aa9f67fcd85cf7ed0708c58

2020-11-30 22:17 UTC, naupaka commented
@FNTrejo8 please fix the merge conflict with the .gitignore file -- you can do it in the web interface or on your local machine

2020-12-05 17:04 UTC, FNTrejo8 commented
@naupaka Fixed the merge conflicts with the gitignore file by c754af3b71fd8321e64bfe1c2a2393a90ff4fffb and 5975de2cbf3e4635c3297737eda41431c6d08e5d

2020-12-06 22:22 UTC, naupaka approved these changes

2020-12-06 22:22 UTC, naupaka commented
👍

2020-12-06 22:23 UTC, merged

2020-12-06 22:24 UTC, naupaka commented
Looks great! https://2020f-usfca-btec-640.github.io/spreadsheet,/notes,/column,/dates,/csv/2020/11/02/best-practices-for-spreadsheet-data.html

2020-12-06 22:25 UTC, naupaka commented
@FNTrejo8 actually looks like there's an issue -- you shouldn't use commas in your tag list, just spaces. See how it messes up the URL? If you submit a quick PR with that fix and @ me, I'll merge it right away

2020-12-06 22:26 UTC, naupaka commented on _posts/2020-11-02-best-practices-for-spreadsheet-data.md
> +categories: spreadsheet, notes, column, dates, CSV
Should just use spaces to separate -- otherwise it messes up the tag list