Ready for review
2020F-usfca-btec-640/2020F-usfca-btec-640.github.io pull request #14
Opened 2020-11-09 05:10 UTC by emhumphrey

Ready for review! I wrote my post on shell computing. @naupaka @melt6457 @mhaliz

2020-11-13 14:18 UTC, DingShen29 requested changes
Overall nice work! You introduced shell very clearly. I just added two comments, hopefully they are helpful in your post.

2020-11-13 14:18 UTC, DingShen29 commented on _posts/2020-11-06-shell-computing.markdown
> +**Command-line interface vs graphical user interface**
Nice explanation for these two types of interface. I would recommend to add a picture for both interface to help beginners virtualize the difference between CLI and GUI.

2020-11-13 14:18 UTC, DingShen29 commented on _posts/2020-11-06-shell-computing.markdown
> +The most commonly used shell tends to be the bourne again shell (bash). Bash tends to be popularly used because it is easy to use for beginners. Bash has great features such as tab completed commands
You may miss a word after "This makes it".

2020-11-14 20:52 UTC, naupaka commented
@emhumphrey quick adjustment -- your PR title should reflect the content you are hoping to merge. Something like "Contribute a blog post on shell computing"

2020-11-15 06:51 UTC, emhumphrey commented
@DingShen29 Thanks for your feedback! I incorporated both changes into my post.

@naupaka Thank you I revised the pr title to reflect the content in my post.

2020-11-21 02:27 UTC, mhaliz approved these changes
Looks good! I'm going to merge these changes now.

2020-11-21 02:39 UTC, merged