Data visualization in R blog post -- Caroline Riedstra
2020F-usfca-btec-640/2020F-usfca-btec-640.github.io pull request #18
Opened 2020-11-09 21:06 UTC by cpriedstra

This post outlines the basics of generating figures in R using ggplot and tidyverse. It includes an introduction to different graphing basics and features of proper figure generation.

2020-12-04 02:07 UTC, cpriedstra commented
Hi @claudiaflautero and @naupaka , thank you for the feedback! I've added a few script examples for the different styles of plots as recommended by @claudiaflautero. Great idea! Please let me know if there is anything else either of you suggest!

2020-12-06 23:59 UTC, naupaka requested changes
Nice job! Some small suggestions to improve some points to be more accurate, and a couple typos. @ mention me when you've made the changes and I'll take another look so we can merge it in.

2020-12-06 23:59 UTC, naupaka commented on _posts/2020-11-05-data-visualization-in-R.md
> +{r name_of_plot}
Don't need this actually -- this is just for Rmarkdown chunks, so I would remove it.

2020-12-06 23:59 UTC, naupaka commented on _posts/2020-11-05-data-visualization-in-R.md
> +1. `{r name_of_plot}`
I'd remove it here too and just renumber your list to start with 1 at 'data'

2020-12-06 23:59 UTC, naupaka commented on _posts/2020-11-05-data-visualization-in-R.md
> +      * ``
Not sure if there was supposed to be something here?

2020-12-06 23:59 UTC, naupaka commented on _posts/2020-11-05-data-visualization-in-R.md
> +  * We have to read in the data file, the easiest way to do this is from a csv or txt file and prior to creating the figure set a variable equal to this file. This way you can call the variable and t
Not exactly. When the command is run to create the data object, it reads from the file and stores the data into memory. That happens when the variable is created, not when the ggplot call occurs. So maybe a slight rewording here would be good.

2020-12-06 23:59 UTC, naupaka commented on _posts/2020-11-05-data-visualization-in-R.md
> +  * Axis labels, can be set `title`, `x=`, and `y=`
Add spaces around the `=`

2020-12-06 23:59 UTC, naupaka commented on _posts/2020-11-05-data-visualization-in-R.md
> +    * `scale_fill_gradient(low = color1", high = "color2")`: color 1 and color 2 are up to you to choose with in a ggplot color scheme. This function can be used when you selected a 'fill' option for
Looks like you're missing an open quotes on color1

2020-12-06 23:59 UTC, naupaka commented on _posts/2020-11-05-data-visualization-in-R.md
> +    * `theme_few()` will remove the gray background from plots as well as the grid
Might want to point out that this is in `ggthemes` and isn't in `ggplot2` by default.

2020-12-07 00:00 UTC, naupaka commented
Also! Sorry this took me so long to get to.

2020-12-07 00:45 UTC, cpriedstra commented
Hi @naupaka, thank you for the feedback! I've made the requested changes: 8cc771437bd656b515c93efa71242ec23befdd16

2020-12-07 01:09 UTC, naupaka requested changes
Couple more minor tweaks to make, and then this should be good to go.

2020-12-07 01:09 UTC, naupaka commented on _posts/2020-11-05-data-visualization-in-R.md
>  3. `aes`
Should fix all the numbering. Currently this skips 2 and jumps to 3.

2020-12-07 01:09 UTC, naupaka commented on _posts/2020-11-05-data-visualization-in-R.md
> +    * `ggthemes` can be used as well for additional customization however it is not part of `ggplot2` and needs to be loaded separately with `library(ggthemes)`:
I'd say `ggthemes` is a package that...

2020-12-07 01:18 UTC, cpriedstra commented
Whoops, great catch, thank you! @naupaka 0321380f11fa01f66bb9001f191be8e28380cdde

2020-12-07 01:32 UTC, naupaka approved these changes

2020-12-07 01:32 UTC, naupaka commented
👍

2020-12-07 01:32 UTC, merged

2020-12-07 01:33 UTC, naupaka commented
https://2020f-usfca-btec-640.github.io/ggplot/figures/r-formatting/2020/11/07/data-visualization-in-R.html