New post ready for review
2020F-usfca-btec-640/2020F-usfca-btec-640.github.io pull request #22
Opened 2020-11-09 22:59 UTC by zhouston2

I'm not sure how to accurately record the date as in the original example post. Also, I don't know if the categories list should be separated by commas. Any advice would be helpful. Thanks, @naupaka @melt6457 @mhaliz 

Zack

2020-11-11 23:52 UTC, tswayd reviewed
This is a good introduction!

2020-11-12 01:35 UTC, tswayd reviewed
The BibTex part seems well done except some things were not as clear to me. This sentence:

" Defining the bibliography file in your Rmarkdown file and properly calling references within tells Rmarkdown to search for the .bib file and the BibTeX format lets it pull author information to populate your citations."

Seems run-on to me. You use "@" for **entries** and "#" to separate **strings** in a **tag**. It might be helpful to clarify when and where to use these symbols.

In the "Calling Your References" section you mention that the **key** is necessary to cite your reference. But then the example you give is using **tag** "[@tag]". This is a little confusing for me. I apologize if I'm not getting it too clearly.

The rest of your blogpost seems very clear and helpful. Thank you for making this post once again! It seems to be a useful topic for citing resources in general!

2020-11-14 20:49 UTC, naupaka commented
@tswayd you should do a formal review of this PR, not just add comments to the discussion. There is a green button on the top right that will allow you to do this.

2020-11-15 00:02 UTC, tswayd reviewed
This is a good introduction!

2020-11-15 00:04 UTC, tswayd requested changes
Good introduction!
The BibTex part seems well done except some things were not as clear to me. This sentence:

" Defining the bibliography file in your Rmarkdown file and properly calling references within tells Rmarkdown to search for the .bib file and the BibTeX format lets it pull author information to populate your citations."

Seems run-on to me. You use "@" for entries and "#" to separate strings in a tag. It might be helpful to clarify when and where to use these symbols.

In the "Calling Your References" section you mention that the key is necessary to cite your reference. But then the example you give is using tag "[@tag]". This is a little confusing for me. I apologize if I'm not getting it too clearly.

The rest of your blogpost seems very clear and helpful. Thank you for making this post once again! It seems to be a useful topic for citing resources in general!

2020-11-15 01:27 UTC, tswayd requested changes
Good introduction!

2020-11-16 18:38 UTC, zhouston2 commented
Fixed the issues you addressed in your review @tswayd Please let me know if the post meets your clarity expectations!

2020-11-17 00:42 UTC, tswayd commented
That looks good thank you.

2020-11-17 07:34 UTC, tswayd approved these changes

2020-11-17 07:34 UTC, tswayd commented on _posts/2020-11-09-beginners-guide-to-citing-open-source-code-in-rmarkdown.MARKUP
> +Defining the bibliography file in your Rmarkdown file and properly calling references within tells Rmarkdown to search for the .bib file and the BibTeX format lets it pull author information to popul
The BibTex part seems well done except some things were not as clear to me. This sentence:

" Defining the bibliography file in your Rmarkdown file and properly calling references within tells Rmarkdown to search for the .bib file and the BibTeX format lets it pull author information to populate your citations."

Seems run-on to me. You use "@" for entries and "#" to separate strings in a tag. It might be helpful to clarify when and where to use these symbols.

2020-11-17 07:34 UTC, tswayd commented on _posts/2020-11-09-beginners-guide-to-citing-open-source-code-in-rmarkdown.MARKUP
> +Notice that the entire header is contained by `---` above and below. This defines the header for Rmarkdown.
In the "Calling Your References" section you mention that the key is necessary to cite your reference. But then the example you give is using tag "[@tag]". This is a little confusing for me. I apologize if I'm not getting it too clearly.

The rest of your blogpost seems very clear and helpful. Thank you for making this post once again! It seems to be a useful topic for citing resources in general!

2020-11-20 00:28 UTC, naupaka requested changes
Great post! I have a suggestion about something to include, and then some technical issues that you will have to resolve before merging. You will need to revert the included files back to the versions they were in the original repository, or it will break things for everyone else. You also should delete the Rproj file.

I believe you should be able to do this by running the following. The commit hash below is the last commit that I made before you forked it, and if you do `git log` and look for my most recent commit, it should match the hash.

```
git checkout 85cee44202a3a950c5720567215b32aaa1899385 .gitignore
git checkout 85cee44202a3a950c5720567215b32aaa1899385 Gemfile
git checkout 85cee44202a3a950c5720567215b32aaa1899385 Gemfile.lock
git checkout 85cee44202a3a950c5720567215b32aaa1899385 _posts/2020-10-19-welcome-to-jekyll.markdown
git rm 2020F-usfca-btec-640.github.io.Rproj
git commit -m "Change things to the way they were when forked"
```

2020-11-20 00:28 UTC, naupaka commented on _posts/2020-11-09-beginners-guide-to-citing-open-source-code-in-rmarkdown.md
> +Depending on what you're citing, it may be as simple as performing a search for the name of the tool or package.
I'd mention the `citation()` function in R. If you run it with a package name, it gives you the citation info, e.g. `citation("dplyr")`

2020-11-20 00:29 UTC, naupaka commented on _posts/2020-11-09-beginners-guide-to-citing-open-source-code-in-rmarkdown.md
> +Depending on what you're citing, it may be as simple as performing a search for the name of the tool or package.
Also you may need to stage things with `git add` after running the above -- I'm not sure off the top of my head.

2020-11-28 23:28 UTC, zhouston2 commented
Hi @naupaka , I reverted the files and pushed. Hopefully it works now! Sorry for the inconvenience.
Zack

2020-11-30 23:02 UTC, naupaka approved these changes

2020-11-30 23:02 UTC, naupaka commented
👍

2020-11-30 23:02 UTC, merged