contribution to class blog "functions in R"--Jaclyn Cherry
2020F-usfca-btec-640/2020F-usfca-btec-640.github.io pull request #23
Opened 2020-11-09 23:23 UTC by Jac-Cherry

My blog post covers an introduction to functions in R.  I go over what a function is, how to create your own function with a step by step example mirroring the state subset function from the apple mobility project, and how to source and call for a function from another R script.

2020-11-16 21:02 UTC, hannahwailan reviewed
This is awesome! Super helpful way to explain functions in R. I added some suggestions that could make your post a bit more clear.

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +In this post you will learn the basics of functions in R.  This will include:
Not sure if you need to do this, but you may want to add your name

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +
I like that you explain what someone will get out of this blog post! It helps organize the info really well!

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +
Another way that it is explained in really simple terms is that you have input data, the function does something to the input to make the output. I really like the function machine box example. 
![image](https://user-images.githubusercontent.com/38087206/99303599-0abceb00-2806-11eb-8819-49c323dfff7d.png)

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +```ruby
I think that because this is supposed to be R code, you should have ```r here, not ruby. But I would check with the TAs/Prof. Z.

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> + `func_name <- function (argument){
Is there a reason why you have the " `" at the beginning and end of this code? When you add the code chunk with the ``` , it will have your code in a separate section so you don't really need the extra ``s

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +The function name can be what ever you want.  If you
It may be helpful to say to name it something descriptive, but brief so that you can tell it apart from other functions.

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +  ).  You use the `<-` symbol to
Because this is written in markdown, you don't need to keep to the character limit in scripts, so you can have this parenthesis on the same line as the first one.

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +Next you need your statement.  Here is where you read in your csv file.  It is
You should probably note that reading in a csv file is a function in itself that is based in R already.

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +
You may also want to note here that they may have to install the dplyr package because it isn't already in R.

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +You now have a function that will go through a csv file and pars out any
Pars is spelled wrong, it should be parse

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +
It may be helpful to add something about checking each new line of code that you add to make sure that it works and to debug.

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +`source("code/what ever the function's script file name was")`
I would add underscores to the what_ever_the_functions_script_file_name or make it shorter to function_script_file_name, since putting spaces in file names will mess things up in R.

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +```ruby
You should include the source code here because it is included in the script that uses the function.

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +`(subsetted_state = state of choice)`
Same with the spaces here, I would switch them, except for the state, since the state may have spaces in the name

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +
It maybe helpful to note that creating functions can make your code and projects more reproducible.

2020-11-16 21:02 UTC, hannahwailan commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +```
It may be helpful to add a photo of an example csv here with some data so that people can have a visual of what you are talking about in each step.

2020-11-20 01:34 UTC, naupaka requested changes
Nice work on this! I had a few simple suggestions to improve the code formatting and also some clarifications about where functions can be stored and called from.

2020-11-20 01:34 UTC, naupaka commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +what a function is, how to set up a function, and how to call for a function
Most people would say 'call a function' instead of 'call for a function'

2020-11-20 01:34 UTC, naupaka commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> + `func_name <- function (argument){
I agree with @hannahwailan you don't need the backticks because you already have them. Also agree you need to change the ruby to r

2020-11-20 01:34 UTC, naupaka commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +that you make is that the programming function is located on its own R script
So functions don't have to be in their own scripts, that's just one way to help keep things organized and allow them to be used in multiple other places, so I might adjust the wording a little here.

2020-11-20 01:34 UTC, naupaka commented on _posts/2020-11-08-introduction-to-functions-in-R.md
> +and can be called for from any other script contained in the same directory.
Can be called from any other script.

(doesn't have to be in the same directory, and most people don't say called for)

2020-11-23 08:06 UTC, Jac-Cherry commented
@hannahwailan @naupaka 
Thank you for your feedback and suggestions.  I have now updated my blog post to reflect your recommendations.
Thanks again!

2020-11-30 22:23 UTC, naupaka commented
👍

2020-11-30 22:23 UTC, naupaka approved these changes

2020-11-30 22:23 UTC, merged