Introduction to GitHub -- Sami Darrow
2020F-usfca-btec-640/2020F-usfca-btec-640.github.io pull request #26
Opened 2020-11-10 00:26 UTC by sbdarrow

A blog post that highlights what GitHub is, what it's used for, and some of the highlights about the website.

2020-11-12 02:22 UTC, sauerbach-code requested changes
Hi Sami, 
This blogpost is generally pretty good, with nice organization and good explanations! There are a couple of things that need to be explained or elaborated on: mainly branches (like a few sentences explaining what they are, main branch, etc.) and using 'git pull' as well as 'git push'. Once those changes are made, this blogpost should be good to go!

2020-11-12 02:22 UTC, sauerbach-code commented on _posts/2020-11-09-introduction-to-github.md
> +![GitHub Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Font_Awesome_5_brands_github.svg/124px-Font_Awesome_5_brands_github.svg.png)
Good use of the logo!

2020-11-12 02:22 UTC, sauerbach-code commented on _posts/2020-11-09-introduction-to-github.md
> +
Insert explanation of branches in this section here, it makes sense to talk about a branch you push to and pull from Github before mentioning pull requests, as this is the typical workflow with GitHub. You can also mention the ability to switch between branches on the command line.

2020-11-12 02:22 UTC, sauerbach-code commented on _posts/2020-11-09-introduction-to-github.md
> +
Make a note of what to do with a branch after a merge - whether to delete it or not.

2020-11-12 02:22 UTC, sauerbach-code commented on _posts/2020-11-09-introduction-to-github.md
> +
Make note about 'git pull' as well. You have to pull stuff from GitHub once a new version gets added, or if you have to start working on a new repository.

2020-11-12 02:22 UTC, sauerbach-code commented on _posts/2020-11-09-introduction-to-github.md
> +## What is GitHub
Nice use of headers throughout the post!

2020-11-12 02:22 UTC, sauerbach-code commented on _posts/2020-11-09-introduction-to-github.md
> +  * **Person 1:** Creates working code for what the project calls for and pushes this code to GitHub
Nice, succinct explanation!

2020-11-19 23:34 UTC, naupaka requested changes
Great job on this. One very minor technical change that you should make before this is ready to merge.

2020-11-19 23:34 UTC, naupaka commented on _posts/2020-11-09-introduction-to-github.md
> +  * **Pushing Code to GitHub:** if you are working on the command line this can be done through the command ‘git push’ followed by the name of the file that you would like to push to GitHub. This all
Not precisely correct. It should be `git push` followed by the name of the remote (often `origin`) and then the name of the branch on the remote to push to (`master` or `main`). Git pushes and pulls commits, not files.

2020-12-06 22:18 UTC, naupaka commented
@sbdarrow please make the fix I suggested so that we can get this merged and get you the point

2020-12-06 22:46 UTC, sbdarrow commented
Hi @naupaka just made the requested changes!

2020-12-06 22:47 UTC, naupaka commented
Thanks! 👍

2020-12-06 22:47 UTC, naupaka approved these changes

2020-12-06 22:47 UTC, merged

2020-12-06 22:48 UTC, naupaka commented
https://2020f-usfca-btec-640.github.io/github/introduction/basics/2020/11/09/introduction-to-github.html