Blog about Data Science ready to be reviewed.
2020F-usfca-btec-640/2020F-usfca-btec-640.github.io pull request #31
Opened 2020-11-10 02:13 UTC by claudiaflautero

Hi, the blog is complete and ready for review.

2020-11-15 05:37 UTC, Alicebada requested changes
Hello Claudia,

Great job with the blog post. 

You just have some corrections to make which I have highlighted.

2020-11-15 05:37 UTC, Alicebada commented on _posts/2020-11-09-introduction_to_data_science.markdown
> +Everyday, around the world, data is being collected more than has ever been. Every transaction that a single person does is connected trough their email address, to their social media, what they like
Probably change this "Everyday, around the world, data is being collected more than has ever been" to "Every day, around the world, data is being collected more than ever"

2020-11-15 05:37 UTC, Alicebada commented on _posts/2020-11-09-introduction_to_data_science.markdown
> +Everyday, around the world, data is being collected more than has ever been. Every transaction that a single person does is connected trough their email address, to their social media, what they like
"Every transaction that a single person does is connected trough their email address, to their social media, what they like and dislike, where they have visited or are looking to visit, and what they can afford or not. All this information is valuable for companies and governments." can be rewritten as below;

"Every transaction a person makes is connected through their email address to their social media. Also, their preferences, past or upcoming vacation destinations, and what they can afford or not are equally recorded. All these pieces of information are available and valuable to companies and governments."

Please feel free to make changes as well.

2020-11-15 05:37 UTC, Alicebada commented on _posts/2020-11-09-introduction_to_data_science.markdown
> +After the raw data is collected and put together, is important to do an analysis to extract valuable information from it. The raw data is important, yes, but the multiple analysis and conclusions tha
There is a typographical error; "After the raw data is collected and put together, is important" to
"After the raw data is collected and put together, it is important"

2020-11-15 05:37 UTC, Alicebada commented on _posts/2020-11-09-introduction_to_data_science.markdown
> +categories: Data Science
You can add "raw data" and "data" to the categories also

2020-11-20 02:02 UTC, naupaka requested changes
Looks good! Please address @Alicebada's suggestions and then I think this is ready to merge.

2020-11-28 04:46 UTC, claudiaflautero commented
The changes were done to the blog. It should be ready to merge.

2020-11-30 22:56 UTC, naupaka commented
👍

2020-11-30 22:56 UTC, merged