Class Blog Contribution - Quentin Smith
2020F-usfca-btec-640/2020F-usfca-btec-640.github.io pull request #32
Opened 2020-11-10 08:10 UTC by Quentin-Smith

Blog Post on how to use the internet to look for help. Includes specific resources as well as general ones.

2020-11-16 18:25 UTC, Qstein requested changes
Hi Quentin, 
I like your blog post, it gets to the point and lists out helpful search engines and online communities that can help someone with their coding issues. Although the blog post certainly gives good suggestions, I personally feel that searching for help on an error message should begin with understanding the error message. Each coding language gives context clues as to how to potentially solve the error message. I suggest including a section to your blog post about how to read an error message from R or another popular coding language. Although the reader probably doesn't want to hear it, suggest to them learning (or reviewing) the basic data types and coding structures of the code they are working with. Understanding the basics of that coding language can alleviate the mystery around many error messages. And thus, lead the coder to better and more relative google searches. 

Lastly, I really like the wide array of resources you list in your blog post. But I wish you had included ways to solve error messages via reading textbooks. Finding a book to help solve the coder's error message is most likely the slowest solution comparatively to googling or posting to reddit. But if the reader is having issues with (for example) ggplot, maybe the best solution for them is to buy a book about ggplot written by Hadley Wickham. The textbook will hopefully solve their issue as well as future errors while using ggplot.

2020-11-16 18:25 UTC, Qstein commented on _posts/2020-11-09-how-to-scour-the-internet-for-help.markdown
> +![computer_gun.jpeg](https://thumbs.dreamstime.com/z/mad-computer-17134750.jpg)
Haha, Yes! My exact feelings after a whole day of google searching for solutions to my code's error messages.

2020-11-16 18:25 UTC, Qstein commented on _posts/2020-11-09-how-to-scour-the-internet-for-help.markdown
> +But first, you should take a small break. Go on a walk, eat a snack or watch a small video just to clear your mind. Fresh eyes can evaluate the problem easier than when you are frustrated. Ideally th
The second sentence feels like a mouth full. I suggest breaking the sentence into two and use more identifying words rather than "it" and "this". "Ideally this would lead you to the answer right away. But, in case the *solution* still eludes you, taking a small break will help you see the problem more clearly."

2020-11-21 21:19 UTC, mhaliz requested changes
Hi @Quentin-Smith ,
Great idea for a post, the art of dealing with error messages is one of the first major hurdles bioinformaticians deal with.
Please address the comments on your post and commit your changes as you fix them!

2020-11-21 21:19 UTC, mhaliz commented on _posts/2020-11-09-how-to-scour-the-internet-for-help.markdown
> +categories: jekyll update
Update with appropriate categories for your blog post: e.g. "error messages help google" or something like that.

2020-11-21 21:19 UTC, mhaliz commented on _posts/2020-11-09-how-to-scour-the-internet-for-help.markdown
> +![computer_gun.jpeg](https://thumbs.dreamstime.com/z/mad-computer-17134750.jpg)
While the image that you found reflects how many programmers feel, I am not going to approve the merge with this image in the post. I don't think it reflects well on USF to have an image of a gun pointing at the computer screen uploaded to the class blog. 
May I suggest some family-friendly alternatives: [Why tho](https://imgur.com/gallery/h92Wx), [confused cat gif](https://tenor.com/view/confused-whitepersanguardian-why-gif-10312546), or anything else sans guns/violence.

2020-12-06 22:17 UTC, naupaka commented
@Quentin-Smith please make the changes suggested by the reviewers so that we can merge this and give you the point

2020-12-09 16:11 UTC, mhaliz requested changes
Hey @Quentin-Smith , please make sure to update the 'categories' section in the header with keywords that relate to your blog post.

2020-12-09 16:11 UTC, mhaliz commented on _posts/2020-11-09-how-to-scour-the-internet-for-help.markdown
> +categories: jekyll update
Bump

2020-12-10 02:31 UTC, naupaka commented
@Quentin-Smith so close! finish this up and we'll get this on the books

2020-12-10 18:58 UTC, naupaka commented
👍 ✅ 🎉

2020-12-10 19:15 UTC, merged