How to Set Up & Use Atom -- Julissa Gonzalez
2020F-usfca-btec-640/2020F-usfca-btec-640.github.io pull request #9
Opened 2020-11-08 23:56 UTC by jgonzalez17

Here is my first draft on how to download Atom, become familiar with its basic writing syntax, and convert it into an HTML.

2020-11-16 20:31 UTC, Jac-Cherry requested changes
Overall this is a good post teaching someone how to set up and use Atom.  My only suggestions are with changing how a couple of the sentences are worded.  This is an easy fix, just read it aloud to yourself to see where the problem spots are.  Great job!

2020-11-16 20:31 UTC, Jac-Cherry commented on _posts/2020-11-07-welcome-to-atom.md
> +Markdown and convert it into an html.
This last sentence here reads a bit weird.  I think it might read more easily if you add an "in" before Markdown, so it says "write in Markdown".  The other clunky part is at the end.  You could try changing it to "convert it into an HTML file" or "covert it into HTML".  These are not huge issues but it might help to make this sentence flow more easily.

2020-11-16 20:31 UTC, Jac-Cherry commented on _posts/2020-11-07-welcome-to-atom.md
> +4. Paste the result wherever you need it
The last suggestion I have is to add a conclusion or end section to recap or summarize what was just covered so the post does not end abruptly.

2020-11-16 20:31 UTC, Jac-Cherry commented on _posts/2020-11-07-welcome-to-atom.md
> +to learning how to write cool syntax.
This is a good transition sentence; however, I would change "get to learning" to "get started on learning".  This will help the sentence flow.

2020-11-16 21:44 UTC, jgonzalez17 commented
@Jac-Cherry Thank you for your kind feedback and helpful suggestions! I just incorporated them into my blog post. Thanks again! (:

2020-11-21 21:20 UTC, melt6457 commented
@Jac-Cherry Nice job on the thoughtful review!!

2020-11-21 21:29 UTC, melt6457 requested changes
@jgonzalez17 excellent work on this post! I have one small suggestion piggybacking off of Jaclyn. Please add a quick conclusion to the end of your blog post just to recap what you have gone over.

2020-12-06 22:21 UTC, naupaka commented
@jgonzalez17 please make the change suggested by @melt6457 so that we can get this approved and merged, and give you the point

2020-12-07 20:29 UTC, jgonzalez17 commented
> @jgonzalez17 please make the change suggested by @melt6457 so that we can get this approved and merged, and give you the point

Sorry for the delay! Just added the blog recap. Thank you so much! 
@naupaka @melt6457

2020-12-09 04:49 UTC, melt6457 approved these changes
@jgonzalez17 nice work on this post! Merging now

2020-12-09 04:50 UTC, merged